Sprint 11
pavelbelenkow/ImageFeed pull request #4
Opened 2023-05-11 21:56 UTC by pavelbelenkow

2023-05-12 19:44 UTC, IBDesignable requested changes

2023-05-12 19:44 UTC, IBDesignable commented on ImageFeed/SplashViewController.swift
> +                let alert = AlertModel(
перед тем как презентить алерт надо не забыть UIBlockingProgressHUD.dismiss(), сделать. Что думаешь?

Чтобы не повторяться можно прямо перед switch result  cltkfnm

2023-05-12 19:44 UTC, IBDesignable commented on ImageFeed/SplashViewController.swift
> +                AlertPresenter(viewController: self).showAlert(model: alert)
`AlertPresenter(viewController: self)` - вот эту часть лучше создать во viewDidLoad и обращаться к ней как параметру

2023-05-12 19:44 UTC, IBDesignable commented on ImageFeed/Services/ProfileService.swift
> +        request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
Хорошо бы URLRequest собирать в отдельном методе :)

2023-05-12 19:44 UTC, IBDesignable commented on ImageFeed/Services/ProfileService.swift
> +                completion(.success(profile))
если здесь weak self разыменовать чуть выше, то не придется потом так мучаться с проверкой на нил у self?.profile, код будет чище

2023-05-12 19:44 UTC, IBDesignable commented on ImageFeed/Services/ProfileImageSevice.swift
> +        task.resume()
обрати внимание что objectTask уже делает resume. 

Нужно убрать его либо из objectTask, либо здесь не дублироваться (здесь и далее по коду)

2023-05-12 19:44 UTC, IBDesignable commented on ImageFeed/Services/OAuth2TokenStorage.swift
> +            }
хорошо!

2023-05-12 19:44 UTC, IBDesignable commented on ImageFeed/Models/ProfileResult.swift
> +    let lastName: String
lastName тоже может приходить опциональным, в документации нет, но можно проверить через настройки профиля на сайте
<img width="751" alt="Снимок экрана 2023-05-09 в 21 07 21" src="https://github.com/pavelbelenkow/ImageFeed/assets/121577115/da681ff6-db6b-4a84-a64c-f3a198df4c59">

2023-05-12 19:44 UTC, IBDesignable commented on ImageFeed/Models/ProfileResult.swift
> +    }
Существуют разные модели нейминга на стороне бекенда – camelCase/snake_case, JsonDecoder в swift умеет подстраиваться под нужные, при этом не придется писать ключи самостоятельно.

подробнее можно изучить в официальной доке JSONDecoder или в [этой заметке](https://nemecek.be/blog/90/how-to-decode-snake-case-with-codable)

2023-05-12 19:44 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +
если ты хочешь оставить фетчинг в этом контролере, а не как предлагается в учебнике, то хорошо бы еще webview-дисмисить.

Я сейчас столкнулась с ошибкой видимо при получении профиля, и программа выглядит зависшей на экране веб-вью.

2023-05-14 21:15 UTC, pavelbelenkow commented on ImageFeed/SplashViewController.swift
> +                let alert = AlertModel(
Да, добавил дисмисс, спасибо за замечание) Когда проверял на ошибку, 5 минут не мог понять, почему не нажимается "ок" на алерте😅

2023-05-14 21:15 UTC, pavelbelenkow commented on ImageFeed/SplashViewController.swift
> +                AlertPresenter(viewController: self).showAlert(model: alert)
Поменял на свойство здесь и в AuthVC ещё)

2023-05-14 21:15 UTC, pavelbelenkow commented on ImageFeed/Services/ProfileService.swift
> +        request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
Сделал сборку реквеста через статик метод у URLRequest и пролил на сервисы.

2023-05-14 21:15 UTC, pavelbelenkow commented on ImageFeed/Services/ProfileService.swift
> +                completion(.success(profile))
Разыменовал, но поле profile получается всё равно придётся проверять, так как он опциональным задан по учебнику(разыменовал и в сервисе аватарки) + получил ответ от наставников вроде дополнительно ничего не требуется ещё фиксить в этом участке.
![image](https://github.com/pavelbelenkow/ImageFeed/assets/121253282/5a6d69e5-ec7d-4f3c-992b-0a50d97d9f79)

2023-05-14 21:16 UTC, pavelbelenkow commented on ImageFeed/Services/ProfileImageSevice.swift
> +        task.resume()
Спасибо за подсказку! Уже поменял на всех сервисах)

2023-05-14 21:16 UTC, pavelbelenkow commented on ImageFeed/Models/ProfileResult.swift
> +    let lastName: String
Я проверял при регистрации и там просто поле last name было обязательным, поэтому опциональным только био было выставлено. Проверил, как это сделала ты, действительно в настройках профиля можно не задавать его)
![image](https://github.com/pavelbelenkow/ImageFeed/assets/121253282/326ba5d8-a71e-48f9-be7b-9386812a8bdb)

2023-05-14 21:16 UTC, pavelbelenkow commented on ImageFeed/Models/ProfileResult.swift
> +    }
Классная заметка! Спасибо большое, код из громоздкого превратился в одну лаконичную строчку:3

2023-05-14 21:16 UTC, pavelbelenkow commented on ImageFeed/Auth/AuthViewController.swift
> +
Сделал дисмиссинг вебвью перед запросом на проверку авторизации, вроде теперь скрывается или при ошибке заново будем попадать на вью авторизации.

2023-05-15 20:36 UTC, IBDesignable commented on ImageFeed/Services/ProfileService.swift
> +                completion(.success(profile))
Да, просто разыменование не поможет. convertProfileResult  - может выполнять не опциональный Profile и тут мы делаем так:

```swift
let profile = self.convertProfileResult(from: body)
self.profile = profile 
completion(.success(profile)) 
```

2023-05-15 20:42 UTC, IBDesignable commented on ImageFeed/Services/ProfileService.swift
>                  completion(.success(profile))
стало выглядеть лучше :)

2023-05-15 21:06 UTC, pavelbelenkow commented on ImageFeed/Services/ProfileService.swift
>                  completion(.success(profile))
Спасибо, но сделал, как ты указала в этом комментарии) https://github.com/pavelbelenkow/ImageFeed/pull/4#discussion_r1194337907

2023-05-15 21:07 UTC, merged